#!/usr/bin/env python3
"""Generate the campaign and flare catalogue pages from the working spreadsheet.

Reads, in order of preference:
    a published Google Sheet, if MFC_SHEET_URL is set (see below)
    data/Full Major Flare Catalogue.xlsx   the team's working catalogue
    data/mfc_catalogue_final.csv           SOAR-verified observed windows

To build straight from Google Sheets, publish the sheet to the web
(File > Share > Publish to web) and set the sheet key:

    export MFC_SHEET_KEY=1AbC...              # the id from the sheet URL
    python scripts/build_catalogue.py

Each worksheet is then fetched as CSV over the network.  Without that
variable the local spreadsheet in data/ is used, so the build stays
reproducible and works offline.

Writes:
    docs/_data/campaigns.csv               flat campaign table
    docs/_data/flares.csv                  flat flare table
    docs/campaigns/index.md                campaign catalogue page
    docs/campaigns/<uid>.md                one page per campaign
    docs/flares/index.md                   flare catalogue page
    docs/flares/<flare_id>.md              one page per flare

Everything under docs/campaigns/ and docs/flares/ is generated -- do not
edit those files by hand.  Run this after editing the spreadsheet:

    python scripts/build_catalogue.py
"""

from __future__ import annotations

import csv
import datetime as dt
import re
from dataclasses import dataclass, field, asdict
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
XLSX = ROOT / "data" / "Full Major Flare Catalogue.xlsx"
SOAR_CSV = ROOT / "data" / "mfc_catalogue_final.csv"
DOCS = ROOT / "docs"

GENERATED_NOTE = (
    "% This page is generated by scripts/build_catalogue.py -- do not edit by hand.\n"
)

SEASON_ORDER = [
    "Spring 2023", "Spring 2024", "Autumn 2024", "Winter 2024",
    "Spring 2025", "Autumn 2025", "Winter 2026", "Summer 2026",
]


# --------------------------------------------------------------------------
# data model
# --------------------------------------------------------------------------

@dataclass
class Flare:
    flare_id: str
    campaign_uid: str
    date: str
    time_ut: str
    goes_class: str
    observed_by: str
    seen_from_earth: str = ""
    so_au: str = ""
    hg_stonyhurst: str = ""

    @property
    def goes_letter(self) -> str:
        m = re.match(r"([A-Z])", self.goes_class.strip().upper())
        return m.group(1) if m else "?"

    @property
    def sort_key(self) -> str:
        return f"{self.date} {self.time_ut}"


@dataclass
class Campaign:
    uid: str
    kind: str            # "Major Flare" or "Trigger"
    ltp: str
    rsw: str
    season: str
    date: str
    window: str
    eui_window: str = ""
    spice_window: str = ""
    phi_window: str = ""
    trigger_instrument: str = ""
    seen_from_earth: str = ""
    so_location: str = ""
    so_au: str = ""
    target_coords: str = ""
    notes: str = ""
    # SOAR verification
    eui_observed: str = ""
    eui_files: str = ""
    eui_cadence: str = ""
    eui_status: str = ""
    spice_observed: str = ""
    spice_files: str = ""
    spice_cadence: str = ""
    phi_observed: str = ""
    phi_files: str = ""
    phi_cadence: str = ""
    instruments_soar: str = ""
    soop: str = ""
    flares: list[Flare] = field(default_factory=list)

    @property
    def type_label(self) -> str:
        if self.kind == "Trigger":
            return f"Trigger ({self.trigger_instrument})" if self.trigger_instrument else "Trigger"
        return "MFC-SOOP"

    @property
    def flare_summary(self) -> str:
        if not self.flares:
            return "none"
        return ", ".join(f.goes_class for f in self.flares)


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def cell_to_text(value) -> str:
    """Normalise an openpyxl cell value to a clean string."""
    if value is None:
        return ""
    if isinstance(value, dt.datetime):
        return value.strftime("%Y-%m-%d")
    if isinstance(value, dt.time):
        return value.strftime("%H:%M")
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value).strip()


def split_multi(value, sep_comma: bool = True) -> list[str]:
    """Split a multi-value cell into one entry per flare.

    Flare information is stored as parallel lists in three adjacent cells
    (time, class, observed-by), one line per flare.  The observed-by cell
    uses commas *within* a line to list several instruments for one flare
    ("EUI, SPICE"), so it must be split on newlines only.
    """
    text = cell_to_text(value)
    if not text or text.lower() in {"none", "n/a", "-"}:
        return []
    parts = re.split(r"[\n,]+" if sep_comma else r"\n+", text)
    return [p.strip() for p in parts if p.strip()]


def roll_date(date: str, time_ut: str, window: str) -> str:
    """Advance the date by a day for flares after a window's midnight rollover.

    A window written "22:30 - 02:30" runs past midnight; a flare at 01:48
    inside it belongs to the following day.
    """
    m = re.match(r"\s*(\d{1,2})[:.](\d{2})", window or "")
    t = re.match(r"(\d{1,2}):(\d{2})", time_ut or "")
    if not m or not t:
        return date
    start_min = int(m.group(1)) * 60 + int(m.group(2))
    flare_min = int(t.group(1)) * 60 + int(t.group(2))
    if flare_min >= start_min:
        return date
    try:
        d = dt.date.fromisoformat(date)
    except ValueError:
        return date
    return (d + dt.timedelta(days=1)).isoformat()


def parse_flares(uid: str, date: str, times, classes, observers,
                 earth: str, au: str, hgs: str, window: str = "") -> list[Flare]:
    """Zip the three parallel flare cells into Flare records."""
    t_list = split_multi(times)
    c_list = split_multi(classes)
    o_list = split_multi(observers, sep_comma=False)
    if not t_list and not c_list:
        return []

    n = max(len(t_list), len(c_list))
    flares = []
    for i in range(n):
        time_ut = t_list[i] if i < len(t_list) else ""
        goes = c_list[i] if i < len(c_list) else ""
        obs = o_list[i] if i < len(o_list) else (o_list[0] if len(o_list) == 1 else "")
        if not time_ut and not goes:
            continue
        # normalise HH:MM
        m = re.match(r"(\d{1,2})[:.](\d{2})", time_ut)
        time_ut = f"{int(m.group(1)):02d}:{m.group(2)}" if m else time_ut
        fdate = roll_date(date, time_ut, window)
        slug = f"{fdate}T{time_ut.replace(':', '-')}" if time_ut else f"{fdate}-{i + 1}"
        flares.append(Flare(
            flare_id=slug, campaign_uid=uid, date=fdate, time_ut=time_ut,
            goes_class=goes, observed_by=obs, seen_from_earth=earth,
            so_au=au, hg_stonyhurst=hgs,
        ))
    return flares


def season_for(ltp: str, date: str) -> str:
    """Derive a season label from the LTP, falling back to the date."""
    mapping = {
        "LTP11": "Spring 2023", "LTP15": "Spring 2024", "LTP17": "Autumn 2024",
        "LTP19": "Spring 2025", "LTP21": "Autumn 2025", "LTP22": "Winter 2026",
        "LTP24": "Summer 2026",
    }
    key = ltp.strip().upper().replace(" ", "")
    if key in mapping:
        # the Dec 2024 trigger block sits in LTP17 but reads as Winter 2024
        if key == "LTP17" and date >= "2024-11-01":
            return "Winter 2024"
        if key == "LTP21" and date >= "2025-11-01":
            return "Winter 2025"
        return mapping[key]
    return ""


# --------------------------------------------------------------------------
# readers
# --------------------------------------------------------------------------

SHEET_KEY_ENV = "MFC_SHEET_KEY"
SHEET_CSV = ("https://docs.google.com/spreadsheets/d/{key}/gviz/tq"
             "?tqx=out:csv&sheet={sheet}")


def fetch_google_sheet(key: str, sheet: str) -> list[list]:
    """Fetch one worksheet of a published Google Sheet as rows.

    Returns the same shape as openpyxl's iter_rows(values_only=True) so the
    two sources are interchangeable.
    """
    import urllib.parse
    import urllib.request

    url = SHEET_CSV.format(key=key, sheet=urllib.parse.quote(sheet))
    with urllib.request.urlopen(url, timeout=30) as resp:
        text = resp.read().decode("utf-8")
    return [row for row in csv.reader(text.splitlines())]


def read_soar() -> dict[str, dict]:
    if not SOAR_CSV.exists():
        return {}
    with SOAR_CSV.open() as fh:
        return {r["Unique ID"]: r for r in csv.DictReader(fh) if r.get("Unique ID")}


def read_rows(rows: list, kind: str, soar: dict[str, dict]) -> list[Campaign]:
    """Build Campaign records from raw worksheet rows.

    Accepts rows from either openpyxl or a Google Sheets CSV fetch.
    """
    rows = [r for r in rows if any(v not in (None, "") for v in r)]
    campaigns: list[Campaign] = []

    # column layout differs slightly between the two sheets
    if kind == "Trigger":
        C = dict(ltp=0, rsw=1, uid=2, date=3, window=4, trig=5,
                 ftime=6, fclass=7, fobs=8, earth=9, loc=10, au=11,
                 hgs=10, target=12, notes=13)
    else:
        C = dict(ltp=0, rsw=1, uid=2, date=3, window=4, eui=5, spice=6, phi=7,
                 ftime=8, fclass=9, fobs=10, earth=11, loc=12, au=13,
                 hgs=12, target=14, notes=15)

    for row in rows[2:]:
        uid = cell_to_text(row[C["uid"]]) if len(row) > C["uid"] else ""
        if not uid or not re.match(r"^MF[WT]\d{8}", uid):
            continue  # season separator or header repeat

        get = lambda k: cell_to_text(row[C[k]]) if C.get(k) is not None and len(row) > C[k] else ""
        date = get("date")
        ltp = get("ltp")

        c = Campaign(
            uid=uid, kind=kind, ltp=ltp, rsw=get("rsw"),
            season=season_for(ltp, date), date=date, window=get("window"),
            eui_window=get("eui"), spice_window=get("spice"), phi_window=get("phi"),
            trigger_instrument=get("trig"), seen_from_earth=get("earth"),
            so_location=get("loc"), so_au=get("au"), target_coords=get("target"),
            notes=get("notes"),
        )
        c.flares = parse_flares(
            uid, date,
            row[C["ftime"]] if len(row) > C["ftime"] else None,
            row[C["fclass"]] if len(row) > C["fclass"] else None,
            row[C["fobs"]] if len(row) > C["fobs"] else None,
            c.seen_from_earth, c.so_au, c.so_location, c.window,
        )

        if uid in soar:
            s = soar[uid]
            c.eui_observed = s.get("EUI observed (UT)", "")
            c.eui_files = s.get("EUI files", "")
            c.eui_cadence = s.get("EUI cadence", "")
            c.eui_status = s.get("EUI status", "")
            c.spice_observed = s.get("SPICE observed (UT)", "")
            c.spice_files = s.get("SPICE files", "")
            c.spice_cadence = s.get("SPICE cadence", "")
            c.phi_observed = s.get("PHI observed (UT)", "")
            c.phi_files = s.get("PHI files", "")
            c.phi_cadence = s.get("PHI cadence", "")
            c.instruments_soar = s.get("Instruments in SOAR", "")
            c.soop = s.get("EUI SOOP in SOAR", "")
            if not c.season:
                c.season = s.get("Season", "")

        campaigns.append(c)
    return campaigns


# --------------------------------------------------------------------------
# writers
# --------------------------------------------------------------------------

def html_link(text: str, href: str) -> str:
    return f'<a href="{href}">{text}</a>'


def interactive_table(
    headers: list[str],
    rows: list[list[str]],
    filters: list[tuple[str, int, list[str]]] | None = None,
    numeric_cols: set[int] | None = None,
) -> str:
    """Render a sortable, searchable HTML table with filter dropdowns.

    Enhanced by _static/catalogue.js.  Without JavaScript it degrades to
    a plain HTML table that still reads correctly.
    """
    numeric_cols = numeric_cols or set()
    out = ['<div class="mfc-table-wrapper">', '<div class="mfc-toolbar">']
    out.append(
        '<input type="search" class="mfc-search" '
        'placeholder="Search..." aria-label="Search the table">'
    )
    for label, col, options in (filters or []):
        out.append(f'<select class="mfc-filter" data-column="{col}" aria-label="{label}">')
        out.append(f'<option value="">{label}: all</option>')
        for opt in options:
            out.append(f'<option value="{opt}">{opt}</option>')
        out.append("</select>")
    out.append('<button type="button" class="mfc-reset">Reset</button>')
    out.append("</div>")
    out.append('<p class="mfc-count"></p>')
    out.append('<div class="mfc-scroll"><table class="mfc-table"><thead><tr>')
    for i, h in enumerate(headers):
        num = ' data-numeric="true"' if i in numeric_cols else ""
        out.append(f"<th{num}>{h}</th>")
    out.append("</tr></thead><tbody>")
    for r in rows:
        out.append("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>")
    out.append("</tbody></table></div>")
    out.append('<p class="mfc-empty" hidden>No rows match those filters.</p>')
    out.append("</div>")
    return "\n".join(out)


def md_table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        out.append("| " + " | ".join(x if x else "" for x in r) + " |")
    return "\n".join(out)


def write_campaign_page(c: Campaign) -> None:
    L = ["---", "html_theme.sidebar_secondary.remove: true", "---", "",
         GENERATED_NOTE, f"# {c.uid}", ""]
    subtitle = f"{c.type_label}, {c.date}"
    if c.season:
        subtitle += f", {c.season}"
    L.append(f"**{subtitle}**")
    L.append("")

    # quick facts
    facts = [
        ("LTP", c.ltp), ("RSW", c.rsw), ("Season", c.season),
        ("Date", c.date), ("Planned window (UT)", c.window),
        ("Instruments in SOAR", c.instruments_soar),
        ("SOOP", f"`{c.soop}`" if c.soop else ""),
        ("Spacecraft distance", f"{c.so_au} AU" if c.so_au else ""),
        ("Spacecraft location (HG Stonyhurst)", c.so_location),
        ("Target coordinates", c.target_coords),
        ("Viewable from Earth", c.seen_from_earth),
    ]
    if c.trigger_instrument:
        facts.insert(4, ("Triggering instrument", c.trigger_instrument))
    L += ["## Quick facts", "",
          md_table(["Property", "Value"], [[k, v] for k, v in facts if v]), ""]

    # planned vs observed
    per_inst = []
    for name, planned, observed, files, cadence in [
        ("EUI", c.eui_window, c.eui_observed, c.eui_files, c.eui_cadence),
        ("SPICE", c.spice_window, c.spice_observed, c.spice_files, c.spice_cadence),
        ("PHI", c.phi_window, c.phi_observed, c.phi_files, c.phi_cadence),
    ]:
        if planned or observed:
            per_inst.append([name, planned, observed, files, cadence])
    if per_inst:
        L += ["## Planned and observed windows", "",
              "Observed windows, file counts and cadences are as verified "
              "against [SOAR](https://soar.esac.esa.int/soar/).", "",
              md_table(["Instrument", "Planned (UT)", "Observed (UT)",
                        "Files", "Cadence"], per_inst), ""]

    if c.notes:
        L += ["## Observer notes", "", c.notes, ""]

    # flares
    L += ["## Flares observed", ""]
    if c.flares:
        rows = [[f"[{f.time_ut}](../flares/{f.flare_id}.md)", f.goes_class, f.observed_by]
                for f in c.flares]
        L += [md_table(["Time (UT)", "GOES class", "Observed by"], rows), ""]
    else:
        L += ["No flare recorded in this window.", ""]

    # products
    L += [
        "## Quicklook products", "",
        ":::{note}",
        "Per-campaign quicklook products (STIX and HRI timeseries, FSI "
        "field-of-view overlays, orbit plots and JHelioviewer movies) are "
        "being generated and will be linked here.",
        ":::", "",
        "## Data access", "",
        f"- **Solar Orbiter data:** [search SOAR for {c.date}]"
        f"(https://soar.esac.esa.int/soar/#search)",
        "- **STIX:** [STIX Data Centre](https://datacenter.stix.i4ds.net/)",
        "- **EUI observing log:** [SIDC EUI wiki]"
        "(https://gitlab-as.oma.be/SIDC/SpaceInstruments/eui/-/wikis/home)",
        "",
        "## Coordinated observations", "",
        "See [Finding coordinated observations](../resources.md) for how to "
        "check IRIS, Hinode, radio and ground-based coverage for this window.",
        "",
        "---", "",
        "**Cite this page**", "",
        "```text",
        f"Hayes, L. et al. (2026). Solar Orbiter Major Flare Campaigns: campaign {c.uid}.",
        f"https://solo-flare-issi.github.io/mfc-website/campaigns/{c.uid}.html",
        "```", "",
    ]
    (DOCS / "campaigns" / f"{c.uid}.md").write_text("\n".join(L))


def write_flare_page(f: Flare, c: Campaign) -> None:
    L = ["---", "html_theme.sidebar_secondary.remove: true", "---", "",
         GENERATED_NOTE,
         f"# {f.date} {f.time_ut} ({f.goes_class or 'unclassified'})", ""]
    facts = [
        ("Date", f.date), ("Time (UT)", f.time_ut), ("GOES class", f.goes_class),
        ("Observed by", f.observed_by), ("Seen from Earth", f.seen_from_earth),
        ("Spacecraft distance", f"{f.so_au} AU" if f.so_au else ""),
        ("Spacecraft location (HG Stonyhurst)", f.hg_stonyhurst),
        ("Campaign", f"[{c.uid}](../campaigns/{c.uid}.md) ({c.type_label})"),
        ("LTP", c.ltp), ("Season", c.season),
    ]
    L += ["## Quick facts", "",
          md_table(["Property", "Value"], [[k, v] for k, v in facts if v]), "",
          "## Lightcurves and imaging", "",
          ":::{note}",
          "STIX and HRI timeseries, and representative imaging for this event, "
          "will be linked here.",
          ":::", "",
          "## Coordinated observations", "",
          "See [Finding coordinated observations](../resources.md).", "",
          "## Publications", "",
          "None recorded yet. See [Contribute](../contribute.md) to add one.", "",
          "---", "", "**Cite this page**", "", "```text",
          f"Hayes, L. et al. (2026). Solar Orbiter Major Flare Campaigns: flare {f.flare_id}.",
          f"https://solo-flare-issi.github.io/mfc-website/flares/{f.flare_id}.html",
          "```", ""]
    (DOCS / "flares" / f"{f.flare_id}.md").write_text("\n".join(L))


def write_campaign_index(campaigns: list[Campaign]) -> None:
    rows = []
    for c in campaigns:
        rows.append([
            html_link(c.uid, f"{c.uid}.html"),
            f'<span class="mfc-tag mfc-tag-{"trigger" if c.kind == "Trigger" else "soop"}">'
            f"{c.type_label}</span>",
            c.date, c.season or c.ltp, c.ltp, c.window,
            c.instruments_soar or "", c.flare_summary,
        ])
    n_soop = sum(1 for c in campaigns if c.kind == "Major Flare")
    n_trig = len(campaigns) - n_soop
    n_flares = sum(len(c.flares) for c in campaigns)
    n_with = sum(1 for c in campaigns if c.flares)

    seasons = sorted({c.season for c in campaigns if c.season})
    ltps = sorted({c.ltp for c in campaigns if c.ltp})

    L = ["---", "html_theme.sidebar_secondary.remove: true", "---", "",
         GENERATED_NOTE, "# Campaign catalogue", "",
         f"Every observing window in the Solar Orbiter Major Flare Campaigns: "
         f"**{n_soop} MFC-SOOP instances** and **{n_trig} flare-trigger windows**, "
         f"{n_with} of which recorded a flare.", "",
         "Click a campaign to open its detail page, which gives the planned and "
         "observed windows for each instrument, the flares captured, and where "
         "to find the data. Column headings sort the table.", "",
         "::::{grid} 2 4 4 4",
         ":gutter: 2", "",
         f":::{{grid-item-card}} {len(campaigns)}",
         ":class-card: mfc-stat", "", "observing windows", ":::", "",
         f":::{{grid-item-card}} {n_soop}",
         ":class-card: mfc-stat", "", "MFC-SOOP instances", ":::", "",
         f":::{{grid-item-card}} {n_trig}",
         ":class-card: mfc-stat", "", "trigger windows", ":::", "",
         f":::{{grid-item-card}} {n_flares}",
         ":class-card: mfc-stat", "", "flares recorded", ":::", "",
         "::::", "",
         interactive_table(
             ["Campaign", "Type", "Date", "Season", "LTP", "Window (UT)",
              "Instruments in SOAR", "Flares"],
             rows,
             filters=[("Type", 1, ["MFC-SOOP", "Trigger"]),
                      ("Season", 3, seasons),
                      ("LTP", 4, ltps)],
         ), "",
         "Prefer a narrative view? [Instances](../instances.md) walks through the "
         "MFC-SOOP campaigns season by season, and "
         "[Trigger Campaigns](../trigger-campaigns.md) covers the EUI and PHI "
         "trigger operations.", "",
         "The same data is available as a CSV download on the "
         "[Data](../data.md) page.", "",
         "```{toctree}", ":hidden:", ":maxdepth: 1", ""]
    L += [c.uid for c in campaigns]
    L += ["```", ""]
    (DOCS / "campaigns" / "index.md").write_text("\n".join(L))


def write_flare_index(campaigns: list[Campaign]) -> None:
    flares = sorted(
        [(f, c) for c in campaigns for f in c.flares], key=lambda p: p[0].sort_key
    )
    rows = [[
        html_link(f"{f.date} {f.time_ut}", f"{f.flare_id}.html"),
        f'<span class="mfc-goes mfc-goes-{f.goes_letter.lower()}">{f.goes_class}</span>',
        f.goes_letter, f.observed_by, f.seen_from_earth,
        f.so_au, html_link(c.uid, f"../campaigns/{c.uid}.html"),
    ] for f, c in flares]

    counts: dict[str, int] = {}
    for f, _ in flares:
        counts[f.goes_letter] = counts.get(f.goes_letter, 0) + 1
    letters = [k for k in ["X", "M", "C", "B", "A"] if k in counts]

    L = ["---", "html_theme.sidebar_secondary.remove: true", "---", "",
         GENERATED_NOTE, "# Flare catalogue", "",
         f"Every flare recorded within a Solar Orbiter Major Flare Campaigns "
         f"window since 2023. Classes for far-side events are estimated from "
         f"STIX. Column headings sort the table.", "",
         "::::{grid} 2 4 4 4", ":gutter: 2", ""]
    L += [f":::{{grid-item-card}} {len(flares)}", ":class-card: mfc-stat", "",
          "flares recorded", ":::", ""]
    for k in letters[:3]:
        L += [f":::{{grid-item-card}} {counts[k]}", ":class-card: mfc-stat", "",
              f"{k}-class", ":::", ""]
    L += ["::::", "",
          ":::{warning} Not yet included",
          "The four flares captured by the PHI trigger campaigns (2024-12-08 "
          "X2.3, 2026-02-03 X1.5, 2026-02-04 X4.2 and 2026-02-06 C2) are "
          "described on the [Trigger Campaigns](../trigger-campaigns.md) page "
          "but have not yet been entered in the working spreadsheet, so they "
          "are absent from the table below.",
          ":::", "",
          interactive_table(
              ["Peak time (UT)", "GOES class", "Class", "Observed by",
               "Seen from Earth", "SO distance (AU)", "Campaign"],
              rows,
              filters=[("Class", 2, letters),
                       ("Seen from Earth", 4, ["Yes", "No"])],
              numeric_cols={5},
          ), "",
          "The same data is available as a CSV download on the "
          "[Data](../data.md) page.", "",
          "```{toctree}", ":hidden:", ":maxdepth: 1", ""]
    L += [f.flare_id for f, _ in flares]
    L += ["```", ""]
    (DOCS / "flares" / "index.md").write_text("\n".join(L))


def write_data_csvs(campaigns: list[Campaign]) -> None:
    out = DOCS / "_data"
    out.mkdir(exist_ok=True)
    camp_fields = [k for k in asdict(campaigns[0]) if k != "flares"]
    with (out / "campaigns.csv").open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=camp_fields)
        w.writeheader()
        for c in campaigns:
            d = asdict(c)
            d.pop("flares")
            w.writerow(d)
    flares = [f for c in campaigns for f in c.flares]
    if flares:
        with (out / "flares.csv").open("w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=list(asdict(flares[0])))
            w.writeheader()
            for f in flares:
                w.writerow(asdict(f))


# --------------------------------------------------------------------------

def main() -> None:
    import os

    soar = read_soar()
    campaigns: list[Campaign] = []

    key = os.environ.get(SHEET_KEY_ENV)
    if key:
        print(f"reading from Google Sheet {key}")
        for sheet, kind in [("Instances", "Major Flare"),
                            ("Trigger instances", "Trigger")]:
            rows = fetch_google_sheet(key, sheet)
            campaigns += read_rows(rows, kind, soar)
    else:
        wb = openpyxl.load_workbook(XLSX)
        for name in wb.sheetnames:
            rows = [r for r in wb[name].iter_rows(values_only=True)
                    if any(v is not None for v in r)]
            if name.strip() == "Instances":
                campaigns += read_rows(rows, "Major Flare", soar)
            elif name.strip().startswith("Trigger"):
                campaigns += read_rows(rows, "Trigger", soar)

    campaigns.sort(key=lambda c: (c.date, c.uid))

    for sub in ("campaigns", "flares"):
        d = DOCS / sub
        d.mkdir(exist_ok=True)
        for old in d.glob("*.md"):
            old.unlink()

    for c in campaigns:
        write_campaign_page(c)
        for f in c.flares:
            write_flare_page(f, c)

    write_campaign_index(campaigns)
    write_flare_index(campaigns)
    write_data_csvs(campaigns)

    n_flares = sum(len(c.flares) for c in campaigns)
    print(f"{len(campaigns)} campaigns, {n_flares} flares")
    print(f"  -> docs/campaigns/  ({len(campaigns) + 1} pages)")
    print(f"  -> docs/flares/     ({n_flares + 1} pages)")
    print(f"  -> docs/_data/campaigns.csv, flares.csv")


if __name__ == "__main__":
    main()
